run tests on multiple OSes

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -9,69 +9,110 @@ on:
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
   BUILD_TYPE: Debug
-  CPU_COUNT: 2
 
 jobs:
   basic-test:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
-    runs-on: ubuntu-latest
+    runs-on: ${{matrix.os}}
+
+    strategy:
+      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
+      fail-fast: false
+
+      matrix:
+        os: [ubuntu-latest, macos-latest]
+        include:
+        - os: ubuntu-latest
+          deps: sudo apt-get install -y ninja-build libgflags-dev
+          cpus: 2
+        - os: macos-latest
+          deps: brew install ninja gflags
+          cpus: 3
 
     steps:
+    - name: Check disk space (before cleaning)
+      if: runner.os == 'macOS'
+      run: df -h
+
+    - name: Free disk space
+      if: runner.os == 'macOS'
+      run: |
+        sudo docker rmi $(docker image ls -aq) || true
+        sudo rm -rf /usr/share/dotnet
+        sudo rm -rf /usr/local/lib/android
+
+    - name: Check disk space (after cleaning)
+      if: runner.os == 'macOS'
+      run: df -h
+
     - uses: actions/checkout@v3
 
     - name: Install dependencies
-      run: sudo apt-get install -y ninja-build libgflags-dev
+      run: ${{matrix.deps}}
 
     - name: Create build directory
       run: mkdir -p ${{github.workspace}}/build
 
     - name: Configure CMake
       working-directory: ${{github.workspace}}/build
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: cmake -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_ALL_TESTS=OFF ../rocksdb-cxx
 
     - name: Build
       working-directory: ${{github.workspace}}/build
-      # Build your program with the given configuration
       run: ninja
 
     - name: Test
       working-directory: ${{github.workspace}}/build
-      # Execute tests defined by the CMake configuration.
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}} -j ${{env.CPU_COUNT}}
+      run: ctest -C ${{env.BUILD_TYPE}} -j ${{matrix.cpus}}
 
   test:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
-    runs-on: ubuntu-latest
+    runs-on: ${{matrix.os}}
+
+    strategy:
+      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
+      fail-fast: false
+
+      matrix:
+        os: [ubuntu-latest, macos-latest]
+        include:
+        - os: ubuntu-latest
+          deps: sudo apt-get install -y ninja-build libgflags-dev
+          cpus: 2
+        - os: macos-latest
+          deps: brew install ninja gflags
+          cpus: 3
 
     steps:
+    - name: Check disk space (before cleaning)
+      if: runner.os == 'macOS'
+      run: df -h
+
+    - name: Free disk space
+      if: runner.os == 'macOS'
+      run: |
+        sudo docker rmi $(docker image ls -aq) || true
+        sudo rm -rf /usr/share/dotnet
+        sudo rm -rf /usr/local/lib/android
+
+    - name: Check disk space (after cleaning)
+      if: runner.os == 'macOS'
+      run: df -h
+
     - uses: actions/checkout@v3
 
     - name: Install dependencies
-      run: sudo apt-get install -y ninja-build libgflags-dev
+      run: ${{matrix.deps}}
 
     - name: Create build directory
       run: mkdir -p ${{github.workspace}}/build
 
     - name: Configure CMake
       working-directory: ${{github.workspace}}/build
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: cmake -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_ALL_TESTS=ON ../rocksdb-cxx
 
     - name: Build
       working-directory: ${{github.workspace}}/build
-      # Build your program with the given configuration
       run: ninja
 
     - name: Test
       working-directory: ${{github.workspace}}/build
-      # Execute tests defined by the CMake configuration.
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}} -j ${{env.CPU_COUNT}}
+      run: ctest -C ${{env.BUILD_TYPE}} -j ${{matrix.cpus}}
